language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson desktop-file-utils libaccounts-glib-dev libclutter-gtk-1.0-dev libdbus-glib-1-dev libgda-5.0-dev libgee-0.8-dev libglib2.0-dev libgpod-dev libgranite-dev libgsignon-glib-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libjson-glib-dev libnotify-dev libpeas-dev libsoup2.4-dev libtagc0-dev libxml2-dev libzeitgeist-2.0-dev valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build && cd build && ninja test"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && meson build && cd build && ninja test"

script:
 - echo BUILDS PASSED
